import { defineMessages } from "../define";

export interface PacketStrings {
  title: string;
  expires: string;
  deadline: string;
  whatsapp: string;
  email: string;
  subject: string;
  body: string;
  portal: string;
  bank: string;
  utr: { label: string; hint: string; placeholder: string };
  portalHelp: string;
  links: string;
  nextSteps: string;
  tabLabels: { whatsapp: string; email: string; portal: string };
  whatsappSend: string;
  emailOpen: string;
  pdf: { download: string; letterhead: string };
  whatNext: { title: string; escalate: string; remind: string; comingSoon: string };
  language: { en: string; hi: string };
  copy: string;
  copied: string;
  unsaved: { title: string; body: string };
  expired: { title: string; body: string; cta: string };
  loadError: { title: string; body: string; retry: string };
}

/** Text for the stopgap packet page. Milestone 4 replaces the page and reuses or rewrites these. */
export const packetMessages = defineMessages<PacketStrings>(
  {
    title: "Your complaint is ready",
    expires: "This link works until {date}. Copy what you need before then.",
    deadline: "Reply deadline you are giving them: {date}",
    whatsapp: "WhatsApp message",
    email: "Email",
    subject: "Subject",
    body: "Message",
    portal: "Answers for the complaint portal form",
    bank: "Answers for the bank complaint form",
    utr: {
      label: "Your UTR (optional)",
      hint: "Only you can see this. It is added to the letter in this browser and never sent anywhere.",
      placeholder: "12 digits from your payment app",
    },
    portalHelp: "Paste these into the matching boxes on the portal. The portal is in English.",
    links: "Official links",
    nextSteps: "What to do next",
    tabLabels: { whatsapp: "WhatsApp", email: "Email + PDF", portal: "Portal" },
    whatsappSend: "Send on WhatsApp",
    emailOpen: "Open in email app",
    pdf: { download: "Download PDF", letterhead: "Generated by Nyay Patra — not a law firm" },
    whatNext: {
      title: "What next?",
      escalate: "Escalate if there's no reply",
      remind: "Remind me on the deadline day",
      comingSoon: "Coming soon — for now, put the date in your own calendar.",
    },
    language: { en: "English", hi: "Hindi" },
    copy: "Copy",
    copied: "Copied ✓",
    unsaved: {
      title: "We could not save a link to your letter",
      body: "Your letter is below and is ready to use. Copy it now, because this page will not be here later.",
    },
    expired: {
      title: "This letter link has expired",
      body: "Letter links work for {days} days and are then deleted. You can make a new letter in a couple of minutes.",
      cta: "Make a new letter",
    },
    loadError: {
      title: "This letter could not load",
      body: "Something went wrong on our side, not because of anything you did. Try again in a moment.",
      retry: "Try again",
    },
  },
  {
    title: "आपकी शिकायत तैयार है",
    expires: "यह लिंक {date} तक चलेगा। उससे पहले ज़रूरी चीज़ें कॉपी कर लें।",
    deadline: "आप उन्हें जवाब के लिए यह तारीख़ दे रहे हैं: {date}",
    whatsapp: "व्हाट्सऐप संदेश",
    email: "ईमेल",
    subject: "विषय",
    body: "संदेश",
    portal: "पोर्टल फ़ॉर्म के जवाब",
    bank: "बैंक शिकायत फ़ॉर्म के जवाब",
    utr: {
      label: "आपका UTR (वैकल्पिक)",
      hint: "यह सिर्फ़ आपको दिखता है। यह इसी ब्राउज़र में पत्र में जुड़ता है, कहीं भेजा नहीं जाता।",
      placeholder: "आपके पेमेंट ऐप के 12 अंक",
    },
    portalHelp: "पोर्टल पर इन्हें संबंधित खानों में पेस्ट करें। पोर्टल अंग्रेज़ी में है।",
    links: "आधिकारिक लिंक",
    nextSteps: "आगे क्या करें",
    tabLabels: { whatsapp: "व्हाट्सऐप", email: "ईमेल + PDF", portal: "पोर्टल" },
    whatsappSend: "व्हाट्सऐप पर भेजें",
    emailOpen: "ईमेल ऐप में खोलें",
    pdf: { download: "PDF डाउनलोड करें", letterhead: "Nyay Patra द्वारा बनाया गया — यह कोई लॉ फ़र्म नहीं है" },
    whatNext: {
      title: "आगे क्या?",
      escalate: "जवाब न मिले तो आगे बढ़ाएँ",
      remind: "तय तारीख़ पर मुझे याद दिलाएँ",
      comingSoon: "जल्द आ रहा है — फ़िलहाल यह तारीख़ अपने कैलेंडर में लिख लें।",
    },
    language: { en: "अंग्रेज़ी", hi: "हिन्दी" },
    copy: "कॉपी करें",
    copied: "कॉपी हो गया ✓",
    unsaved: {
      title: "हम आपके पत्र का लिंक सहेज नहीं पाए",
      body: "आपका पत्र नीचे तैयार है। अभी कॉपी कर लें, क्योंकि यह पेज बाद में उपलब्ध नहीं होगा।",
    },
    expired: {
      title: "इस पत्र का लिंक समाप्त हो गया",
      body: "पत्र के लिंक {days} दिन चलते हैं, फिर मिटा दिए जाते हैं। आप कुछ ही मिनटों में नया पत्र बना सकते हैं।",
      cta: "नया पत्र बनाएँ",
    },
    loadError: {
      title: "यह पत्र लोड नहीं हो सका",
      body: "हमारी तरफ़ से कुछ गड़बड़ हुई, आपकी वजह से नहीं। थोड़ी देर में फिर कोशिश करें।",
      retry: "फिर कोशिश करें",
    },
  }
);
