import { defineMessages } from "../define";

export interface PacketStrings {
  title: string;
  expires: string;
  deleteNow: { summary: string; warning: string; button: string };
  deleted: { title: string; body: string; home: string };
  deadline: string;
  whatsapp: string;
  email: string;
  subject: string;
  body: string;
  portal: string;
  bank: string;
  utr: { label: string; hint: string; placeholder: string; invalid: string };
  portalHelp: string;
  links: string;
  nextSteps: string;
  tabLabels: { whatsapp: string; email: string; portal: string };
  whatsappSend: string;
  emailOpen: string;
  emailMailtoNote: string;
  pdf: { download: string; letterhead: string };
  whatNext: {
    title: string;
    remind: string;
    remindHint: string;
    companyFallback: string;
    remindTitle: string;
    remindBody: string;
    outcome: string;
    outcomeHint: string;
    outcomeSubject: string;
    outcomeBody: string;
  };
  language: { en: string; hi: string };
  copy: string;
  copied: string;
  unsaved: { title: string; body: string };
  expired: { title: string; body: string; cta: string };
  loadError: { title: string; body: string; retry: string };
}

/** Text for the packet page (tabbed WhatsApp/Email+PDF/Portal view). */
export const packetMessages = defineMessages<PacketStrings>(
  {
    title: "Your complaint is ready",
    expires: "This link works until {date}. Copy what you need before then.",
    deleteNow: {
      summary: "Delete this letter now",
      warning: "This removes your letter from our servers straight away. The link stops working and we cannot get it back, so copy what you need first.",
      button: "Yes, delete it now",
    },
    deleted: {
      title: "Your letter is deleted",
      body: "It is gone from our servers and the link no longer works. Anything you already copied or sent is untouched.",
      home: "Back to the home page",
    },
    deadline: "Reply deadline you are giving them: {date}",
    whatsapp: "WhatsApp message",
    email: "Email",
    subject: "Subject",
    body: "Message",
    portal: "Answers for the complaint portal form",
    bank: "Answers for the bank complaint form",
    utr: {
      label: "Your UTR (optional)",
      hint: "Only you can see this. It is added to the letter in this browser and is never sent to us.",
      placeholder: "12 digits from your payment app",
      invalid: "That doesn't look like a UTR — it should be 8-35 letters/digits. The letter will say \"not available\" until this is fixed.",
    },
    portalHelp: "Paste these into the matching boxes on the portal. The portal is in English.",
    links: "Official links",
    nextSteps: "What to do next",
    tabLabels: { whatsapp: "WhatsApp", email: "Email + PDF", portal: "Portal" },
    whatsappSend: "Send on WhatsApp",
    emailOpen: "Open in email app",
    emailMailtoNote:
      "[Your full complaint letter has been copied to your clipboard — paste it here, replacing this line, before sending.]",
    pdf: { download: "Download PDF", letterhead: "Generated by Nyay Patra — not a law firm" },
    whatNext: {
      title: "What next?",
      remind: "Add the deadline to my calendar",
      remindHint: "Saves a small file your calendar app opens. It is made in your browser and nothing is sent to us.",
      companyFallback: "the company",
      remindTitle: "Reply deadline: {company}",
      remindBody:
        "Today is the date you gave {company} to reply. If they have not, the next step is:\n{step}\n\nYour Nyay Patra link may have expired by now, so keep your own copy of the letter.",
      outcome: "Tell us how it went",
      outcomeHint: "Opens an email to us. Share only what you are comfortable with, and leave out your name, phone number and account details.",
      outcomeSubject: "How it went with my complaint",
      outcomeBody:
        "Did it work? (yes / partly / no)\n\nWhat happened:\n\nMay we share this without your name? (yes / no)\n\nPlease do not include your name, phone number or account details.",
    },
    language: { en: "English", hi: "Hindi" },
    copy: "Copy",
    copied: "Copied ✓",
    unsaved: {
      title: "We could not save a link to your letter",
      body: "Your letter is below and is ready to use. Copy it now, because this page will not be here later.",
    },
    expired: {
      title: "This letter link has expired",
      body: "Letter links work for {days} days and are then deleted. You can make a new letter in a couple of minutes.",
      cta: "Make a new letter",
    },
    loadError: {
      title: "This letter could not load",
      body: "Something went wrong on our side, not because of anything you did. Try again in a moment.",
      retry: "Try again",
    },
  },
  {
    title: "आपकी शिकायत तैयार है",
    expires: "यह लिंक {date} तक चलेगा। उससे पहले ज़रूरी चीज़ें कॉपी कर लें।",
    deleteNow: {
      summary: "यह पत्र अभी हटाएँ",
      warning: "इससे आपका पत्र हमारे सर्वर से तुरंत हट जाएगा। लिंक काम करना बंद कर देगा और इसे वापस नहीं लाया जा सकता, इसलिए पहले ज़रूरी चीज़ें कॉपी कर लें।",
      button: "हाँ, अभी हटाएँ",
    },
    deleted: {
      title: "आपका पत्र हटा दिया गया",
      body: "यह हमारे सर्वर से हट गया है और लिंक अब काम नहीं करता। जो कुछ आपने पहले कॉपी या भेजा है, उस पर कोई असर नहीं पड़ा।",
      home: "होम पेज पर वापस जाएँ",
    },
    deadline: "आप उन्हें जवाब के लिए यह तारीख़ दे रहे हैं: {date}",
    whatsapp: "व्हाट्सऐप संदेश",
    email: "ईमेल",
    subject: "विषय",
    body: "संदेश",
    portal: "पोर्टल फ़ॉर्म के जवाब",
    bank: "बैंक शिकायत फ़ॉर्म के जवाब",
    utr: {
      label: "आपका UTR (वैकल्पिक)",
      hint: "यह सिर्फ़ आपको दिखता है। यह इसी ब्राउज़र में पत्र में जुड़ता है, हमें कभी नहीं भेजा जाता।",
      placeholder: "आपके पेमेंट ऐप के 12 अंक",
      invalid: "यह UTR जैसा नहीं लगता — यह 8-35 अक्षर/अंकों का होना चाहिए। जब तक यह ठीक नहीं होता, पत्र में \"उपलब्ध नहीं\" लिखा रहेगा।",
    },
    portalHelp: "पोर्टल पर इन्हें संबंधित खानों में पेस्ट करें। पोर्टल अंग्रेज़ी में है।",
    links: "आधिकारिक लिंक",
    nextSteps: "आगे क्या करें",
    tabLabels: { whatsapp: "व्हाट्सऐप", email: "ईमेल + PDF", portal: "पोर्टल" },
    whatsappSend: "व्हाट्सऐप पर भेजें",
    emailOpen: "ईमेल ऐप में खोलें",
    emailMailtoNote:
      "[आपका पूरा शिकायत पत्र क्लिपबोर्ड में कॉपी हो गया है — भेजने से पहले इसे यहां पेस्ट करें, इस लाइन की जगह।]",
    pdf: { download: "PDF डाउनलोड करें", letterhead: "Nyay Patra द्वारा बनाया गया — यह कोई लॉ फ़र्म नहीं है" },
    whatNext: {
      title: "आगे क्या?",
      remind: "तारीख़ अपने कैलेंडर में जोड़ें",
      remindHint: "एक छोटी फ़ाइल सेव होती है जिसे आपका कैलेंडर ऐप खोलता है। यह आपके ब्राउज़र में बनती है और हमें कुछ नहीं भेजा जाता।",
      companyFallback: "कंपनी",
      remindTitle: "जवाब की आख़िरी तारीख़: {company}",
      remindBody:
        "आज वह तारीख़ है जो आपने {company} को जवाब देने के लिए दी थी। अगर जवाब नहीं आया, तो अगला कदम यह है:\n{step}\n\nहो सकता है आपका Nyay Patra लिंक अब तक बंद हो चुका हो, इसलिए पत्र की अपनी कॉपी रखें।",
      outcome: "हमें बताएँ कैसा रहा",
      outcomeHint: "यह हमें ईमेल खोलता है। उतना ही बताएँ जितना आप सहज हों, और अपना नाम, फ़ोन नंबर और खाते की जानकारी न लिखें।",
      outcomeSubject: "मेरी शिकायत का नतीजा",
      outcomeBody:
        "क्या काम हुआ? (हाँ / कुछ हद तक / नहीं)\n\nक्या हुआ:\n\nक्या हम इसे आपका नाम हटाकर साझा कर सकते हैं? (हाँ / नहीं)\n\nकृपया अपना नाम, फ़ोन नंबर या खाते की जानकारी न लिखें।",
    },
    language: { en: "अंग्रेज़ी", hi: "हिन्दी" },
    copy: "कॉपी करें",
    copied: "कॉपी हो गया ✓",
    unsaved: {
      title: "हम आपके पत्र का लिंक सहेज नहीं पाए",
      body: "आपका पत्र नीचे तैयार है। अभी कॉपी कर लें, क्योंकि यह पेज बाद में उपलब्ध नहीं होगा।",
    },
    expired: {
      title: "इस पत्र का लिंक समाप्त हो गया",
      body: "पत्र के लिंक {days} दिन चलते हैं, फिर मिटा दिए जाते हैं। आप कुछ ही मिनटों में नया पत्र बना सकते हैं।",
      cta: "नया पत्र बनाएँ",
    },
    loadError: {
      title: "यह पत्र लोड नहीं हो सका",
      body: "हमारी तरफ़ से कुछ गड़बड़ हुई, आपकी वजह से नहीं। थोड़ी देर में फिर कोशिश करें।",
      retry: "फिर कोशिश करें",
    },
  }
);
