import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";

/**
 * Builds the source text of the generated templates module from every
 * `<templateId>.<locale>.md` file in `dir`. Pure apart from reading `dir`;
 * CRLF is normalized so the output is byte-identical on every OS.
 */
export function buildTemplatesModuleSource(dir: string): string {
  const files = readdirSync(dir)
    .filter((file) => file.endsWith(".md"))
    .sort();
  const entries = files.map((file) => {
    const key = file.slice(0, -".md".length);
    const raw = readFileSync(join(dir, file), "utf-8").replace(/\r\n/g, "\n");
    return `  ${JSON.stringify(key)}: ${JSON.stringify(raw)},`;
  });
  return [
    "// AUTO-GENERATED by scripts/generate-templates.ts from data/templates/*.md.",
    "// Do not edit by hand — run `npm run generate:templates -w @nyaypatra/core`.",
    "export const TEMPLATES: Record<string, string> = {",
    ...entries,
    "};",
    "",
  ].join("\n");
}
